### ISSUE TITLE
Will release the generated optical flow data?

### ISSUE THREAD

**Issue by lhao0301** [lhoangan/arap_flow#1]
Thanks for your wonderful code!

Will the generated optical flow data on DAVIS or  QUVA be released? Hope to train PWC-net.

**Comment by lhoangan** [comment]
We did not train on QUVA dataset. The DAVIS training set is coming soon. We
will let you know once it is done.

**Comment by lhao0301** [comment]
Okay!
For QUVA: I misunderstand the statement in section 5.4 .

**Comment by lhoangan** [comment]
Hi @lhao0301 , the dataset has been out. Please check this link: https://github.com/lhoangan/arap_flow#dataset

**Comment by lhoangan** [comment]
Hi @lhao0301 , the dataset has been out. Please check this link: https://github.com/lhoangan/arap_flow#dataset
