### ISSUE TITLE
Question on run para_gen.py

### ISSUE THREAD

**Issue by user67979868** [lhoangan/arap_flow#4]
I run `python para_gen.py  --input data/briage8level --output data/briage8level/fd1` in the bash, but there was an error: "`llvm: No such file or directory ......... AssertionError: ARAP exited with code 1.`
my parameter configuration is shown in the picture below.
![2024-09-24_13-19](https://github.com/user-attachments/assets/927dd303-4e5f-46d1-a102-291dfeae08dc)
I thought it could be the problem of dependency of library, and run `ldd arap_deform` in the dash, but the dependencies seem to be found already, like the picture below.
![2024-09-24_13-29(1)](https://github.com/user-attachments/assets/48514d9a-ed37-48e3-b3f7-b728284c541a)
I am not familiar with c++ and opt language. Maybe I made a mistake when "make" the file "arap_form", then cause the problem of arap_deform. I would be very grateful if you can help me.

**Comment by lhoangan** [comment]
Hi @user67979868, thank you for your interest and for reaching out. I just wanted to say upfront that it's been quite a while and I'm not sure if I remember the running process well. That said, I'll try my best to assist you with the problem.

As you may have seen, the python code is only a wrapper to call the C++ code en masse. So if possible, could you please confirm if the command can actually be run when called from the command lines? 
For example, it looks like that `arap_deform` is well built, in that case, you can run this [example](https://github.com/lhoangan/arap_flow/tree/master/ARAP/deformation#readme) from the command lines successfully.

On the other hand, the error of `llvm: no such file or directory` seems to have been discussed in this [issues](https://github.com/niessner/Opt/issues/120)  of the original Opt repo. Maybe it'll give you some idea how to fix it? On my side, reading through it, I remember that I might have had a similar problem with CUDA 9.0 or higher. The version that worked for me was CUDA 7.5 (as mentioned in the README.md). 

Feel free to follow up if it's not clear and please let me know when/how you solve the problem. Thank you.

**Comment by user67979868** [comment]
Thank you very much for your help!  I'll try to change the version of CUDA.

**Comment by user67979868** [comment]
I solved the above problem by changing the cuda version from 11.7 to 7.5, thanks for your advice!
